define([], function() {
	return {
		"data": [
		{
			"Timestamp": "11\/26\/2012 15:29:19",
			"oosView": "",
			"Exercise Name": "Leg Press",
			"fkClientID": "client506",
			"Exercise ID": "exercise145",
			"fk Studio ID": "studio13",
			"netChangeWeight": "",
			"Current Weight": "170",
			"performanceView": "D",
			"Date": "11\/26\/2012",
			"fk Client Name": "Blaine Hart",
			"Total Time": "00:02:26",
			"Current Range": "",
			"dayOfWeek": "Mon",
			"hourOfDay": "3 PM"
		}, {
			"Timestamp": "12\/10\/2012 15:31:34",
			"oosView": "",
			"Exercise Name": "Leg Press",
			"fkClientID": "client506",
			"Exercise ID": "exercise145",
			"fk Studio ID": "studio13",
			"netChangeWeight": "",
			"Current Weight": "170",
			"performanceView": "D",
			"Date": "12\/10\/2012",
			"fk Client Name": "Blaine Hart",
			"Total Time": "00:02:23",
			"Current Range": "",
			"dayOfWeek": "Mon",
			"hourOfDay": "3 PM"
		}, 
		{
			"Timestamp": "09\/11\/2013 13:58:26",
			"oosView": "",
			"Exercise Name": "Leg Press",
			"fkClientID": "client506",
			"Exercise ID": "exercise145",
			"fk Studio ID": "studio13",
			"netChangeWeight": "-13",
			"Current Weight": "150",
			"performanceView": "D",
			"Date": "09\/11\/2013",
			"fk Client Name": "Blaine Hart",
			"Total Time": "00:03:15",
			"Current Range": "",
			"dayOfWeek": "Wed",
			"hourOfDay": "1 PM"
		}, {
			"Timestamp": "09\/16\/2013 14:29:29",
			"oosView": "",
			"Exercise Name": "Leg Press",
			"fkClientID": "client506",
			"Exercise ID": "exercise145",
			"fk Studio ID": "studio13",
			"netChangeWeight": "3",
			"Current Weight": "155",
			"performanceView": "D",
			"Date": "09\/16\/2013",
			"fk Client Name": "Blaine Hart",
			"Total Time": "00:03:14",
			"Current Range": "",
			"dayOfWeek": "Mon",
			"hourOfDay": "2 PM"
		}, {
			"Timestamp": "09\/18\/2013 14:24:09",
			"oosView": "",
			"Exercise Name": "Leg Press",
			"fkClientID": "client506",
			"Exercise ID": "exercise145",
			"fk Studio ID": "studio13",
			"netChangeWeight": "1",
			"Current Weight": "157",
			"performanceView": "D",
			"Date": "09\/18\/2013",
			"fk Client Name": "Blaine Hart",
			"Total Time": "00:03:11",
			"Current Range": "",
			"dayOfWeek": "Wed",
			"hourOfDay": "2 PM"
		}, {
			"Timestamp": "09\/23\/2013 14:32:03",
			"oosView": "",
			"Exercise Name": "Leg Press",
			"fkClientID": "client506",
			"Exercise ID": "exercise145",
			"fk Studio ID": "studio13",
			"netChangeWeight": "",
			"Current Weight": "157",
			"performanceView": "D",
			"Date": "09\/23\/2013",
			"fk Client Name": "Blaine Hart",
			"Total Time": "00:03:10",
			"Current Range": "",
			"dayOfWeek": "Mon",
			"hourOfDay": "2 PM"
		}, {
			"Timestamp": "09\/25\/2013 14:24:38",
			"oosView": "",
			"Exercise Name": "Leg Press",
			"fkClientID": "client506",
			"Exercise ID": "exercise145",
			"fk Studio ID": "studio13",
			"netChangeWeight": "5",
			"Current Weight": "165",
			"performanceView": "D",
			"Date": "09\/25\/2013",
			"fk Client Name": "Blaine Hart",
			"Total Time": "00:03:07",
			"Current Range": "",
			"dayOfWeek": "Wed",
			"hourOfDay": "2 PM"
		}]
	};
});